version: '3.8'

services:
  webapp:
    image: beunyeong/9kcal:4
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/tasteful-ai
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=eun0920!
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=tasteful-ai-image-bucket
      - S3_REGION=ap-northeast-2
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=eun0920!
      - MYSQL_DATABASE=tasteful-ai
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
