services:
  webapp:
    image: kahyunjung/9kcal:4
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/tastefulai
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_BUCKET_NAME=tasteful-ai-image-bucket
      - S3_REGION=ap-northeast-2
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - mysql
      - redis
volumes:
  mysql_data:
  redis_data:
