name: Java CI/CD with Gradle

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Run chmod to make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: gradlew bootJar
        run: ./gradlew bootJar

      - name: Docker Image Build & Push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build  --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/9kcal:4 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/9kcal:4

  deploy-to-app-server-1:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: Deploy to App Server 1
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST_1 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            docker pull kahyunjung/9kcal:4
            docker-compose up --build -d

  deploy-to-app-server-2:

    needs: deploy-to-app-server-1

    runs-on: self-hosted
    steps:
      - name: Deploy to App Server 2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST_2 }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            docker pull kahyunjung/9kcal:4
            docker-compose up --build -d